FileVersion = 1

[Project]
Name = "tomlc99-beef"
DefaultNamespace = "tomlc99"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\tomlc99.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\tomlc99.lib"]
